### PR TITLE
feat: add battery health optimization support

### PR DESCRIPTION
**Pull request by dleviminzi**
This will add support for battery health optimization in laptops that support the feature.

### CODE REVIEW

**Comment by b3nis** [comment]
Interesting!
I wonder if there is any list of supported devices? I guess it’s in the bios settings if it’s exists.

**Comment by dleviminzi** [comment]
> Interesting!
> 
> I wonder if there is any list of supported devices? I guess it’s in the bios settings if it’s exists. 

I know that all 2023 devices support the feature. I think late 2022 devices do too if you update bios. The best way to determine if it will work on your machine is to update everything and then check if the option is present in synapse.

**Comment by phush0** [comment]
rebase please

**Comment by phush0** [comment]
LGTM

**Pull request merged**
